# Page settings

baseurl = "https://trepik.github.io/tomas/"
languageCode = "en-us"
title = "Tomáš's CV"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Career profile"
    author = "Tomáš Repík"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Tomáš Repík"
        tagline = "Data scientist"
        avatar = "profile.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "location"
        icon = "fa-home"
        url = "https://goo.gl/maps/6gFmW6i9JaC2"
        title = "Bratislava, Slovakia"

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
#        url = "mailto: tomas@repik.sk"
#        title = "tomas@repik.sk"
        url = "mailto: tomm.momi@gmail.com"
        title = "tomm.momi@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+421903804847"
        title = "+421 903 804 847"

#        [[params.contact.list]]
#        class = "website"
#        icon = "fa-globe"
#        url = "//portfoliosite.com"
#        title = "portfoliosite.com"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/trepik"
        title = "github.com/trepik"

    # Languages section
    [params.languages]
        enable = true
        title = "Languages"

        [[params.languages.list]]
        language = "Slovak"
        level = "Native"

        [[params.languages.list]]
        language = "Czech"
        level = "Native"

        [[params.languages.list]]
        language = "English"
        level = "Professional"

        [[params.languages.list]]
        language = "Spanish"
        level = "Passive"

        [[params.languages.list]]
        language = "German"
        level = "Passive"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Outdoor activities"

        [[params.interests.list]]
        interest = "Motorsport"

        [[params.interests.list]]
        interest = "Guitar Music"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "After a languages oriented high school I went to study information technologies in Brno. Besides pursuing knowledge and a degree I pursued victories in online races in my free time. Three years passed and I successfuly graduated as a **Bachelor of Information Technology**. My stray shoes took me overseas to study Spanish and computer science at the **University of Tennessee Chattanooga**. After a year abroad I came back to Brno to complete my master studies there. During my entire studies I always freshened my mind on hikes with scouts. I also found a job in Brno at **Red Hat** where I started doing open source. After completing my studies and becoming a **Master of Bioinformatics** I moved back to Bratislava. In september 2017 I joined **Instarea** a big data monetization company, where I'm working as a Data scientist."

    # Education section
    [params.education]
        enable = true
        icon = "fa-graduation-cap"
        title = "Education"

        [[params.education.list]]
        degree = "Master of Bioinformatics and Biocomputing"
        college = "Brno University of Technology"
        dates = "2015 - 2017"

        [[params.education.list]]
        degree = "Online courses of Cluster Analysis and Data Mining"
        college = "Coursera"
        dates = "2015"

        [[params.education.list]]
        degree = "Semester at Computer Science Department"
        college = "University of Tennessee Chattanooga"
        dates = "2015"

        [[params.education.list]]
        degree = "Bachelor of Information Technology"
        college = "Brno University of Technology"
        dates = "2010 - 2014"

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Data scientist / Software Engineer"
        dates = "2017 - present"
        company = "Instarea, Bratislava"
        details = "Joining a big data monetization company and becoming a data scientist is my dream come true. Directing huge loads of data to find its place and show its value is my main goal. To get this done I'm always investigating new technologies, looking for some alternative aproaches or shortcuts to get better performance, keeping in mind both stability and maintainability. I'm also responsible for bussines intelligence and data visualization, done primarly in PowerBI."

        [[params.jobs.list]]
        position = "Associate Software Engineer"
        dates = "2015 - 2017"
        company = "Red Hat, Brno"
        details = "It was my first \"in field\" job experience. I was a package maintainer for both Fedora and Red Hat Enterprise Linux. I was maintainig some Java and C packages, but my work included also some bash or Python. Besides the basic bug-fixing or RPMS, I came across technologies like Software Collections or Containers."

        [[params.jobs.list]]
        position = "Scout Troop Leader"
        dates = "2010 - present"
        company = "29. troop Albatrosi, Bratislava"
        details = "I joined scouts when I was 10 and since then I love being one of them. I went under a proper scout leadership education, earning a decree allowing me to do 'my job'. Being a troop leader requires lots of creativity, communication and managerial skills. The scout movement raise, educate and train children and the youth to become independent, responsible, active and open minded citizens. I think that in my case it proved to be true."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
#        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Maxpoweleague"
        url = "https://www.maxpowerleague.cz"
        tagline = "Since 2008 I was part of the online racing community around rFactor racing simulator. Ever since I joined I participated in organization of the events. I wrote reports, managed our website and result system, cut video reports and commented on live broadcasts."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Data visualization tools (PowerBI)"
        level = "90%"

        [[params.skills.list]]
        skill = "New technologies (ClickHouse, MapD, Cassandra, Hugo)"
        level = "80%"

        [[params.skills.list]]
        skill = "Programming languages (Bash, C, Java, Python, GO)"
        level = "80%"

        [[params.skills.list]]
        skill = "SQL Database (SQL Server, MySQL)"
        level = "70%"

        [[params.skills.list]]
        skill = "Web development (HTML, CSS, JavaScript, PHP)"
        level = "70%"

        [[params.skills.list]]
        skill = "Multimedia tools (Adobe Premiere, Photoshop)"
        level = "60%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
