# Page settings

baseurl = "https://trepik.github.io/cv"
languageCode = "en-us"
title = "Curriculum Vitae"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "My professional profile"
    author = "Tomáš Repík"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Tomáš Repík"
        tagline = "\"Almost\" Engineer of Bioinformatics"
        avatar = "profile.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "location"
        icon = "fa-home"
        url = "https://goo.gl/maps/6gFmW6i9JaC2"
        title = "Bratislava, Slovakia"

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: tomas@repik.sk"
        title = "tomas@repik.sk"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+421903804847"
        title = "+421 903 804 847"

#        [[params.contact.list]]
#        class = "website"
#        icon = "fa-globe"
#        url = "//portfoliosite.com"
#        title = "portfoliosite.com"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/trepik"
        title = "github.com/trepik"

    # Languages section
    [params.languages]
        enable = true
        title = "Languages"

        [[params.languages.list]]
        language = "Slovak"
        level = "Native"

        [[params.languages.list]]
        language = "Czech"
        level = "Native"

        [[params.languages.list]]
        language = "English"
        level = "Professional"

        [[params.languages.list]]
        language = "Spanish"
        level = "Passive"

        [[params.languages.list]]
        language = "German"
        level = "Passive"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Outdoor activities"

        [[params.interests.list]]
        interest = "Motorsport"

        [[params.interests.list]]
        interest = "Guitar Music"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "After a languages oriented high school I went to study information technologies to Brno. Three years passed and I successfuly graduated as a **Bachelor of Information Technology**. My stray shoes took me overseas to study for one semester at the **University of Tennessee Chattanooga**. During one year abroad I improved not only my English but also my Spanish. To finish my Master studies I came back to Brno and signed for the **Bioinformatics program**. In november 2015 I started doing open source as an intern at **Red Hat**. After finishing my Master studies I want to move back to Bratislava and therefore I'm looking for a job there."

    # Education section
    [params.education]
        enable = true
        icon = "fa-graduation-cap"
        title = "Education"

        [[params.education.list]]
        degree = "Master of Bioinformatics and Biocomputing"
        college = "Brno University of Technology"
        dates = "2015 - present"

        [[params.education.list]]
        degree = "Online courses of Cluster Analysis and Data Mining"
        college = "Coursera"
        dates = "2015"

        [[params.education.list]]
        degree = "Semester at Computer Science Department"
        college = "University of Tennessee Chattanooga"
        dates = "2015"

        [[params.education.list]]
        degree = "Bachelor of Information Technology"
        college = "Brno University of Technology"
        dates = "2010 - 2014"

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Associate Software Engineer"
        dates = "2015 - Present"
        company = "Red Hat, Brno"
        details = "It is my first \"in field\" job experience. I'm a package maintainer for both Fedora and Red Hat Enterprise Linux. I'm maintainig some Java and C packages, but my work includes also some bash or Python. Besides the basic bug-fixing or rpms, I came across technologies like software collections or containers."

        [[params.jobs.list]]
        position = "Scout Troop Leader"
        dates = "2010 - present"
        company = "29. troop Albatrosi, Bratislava"
        details = "I joined scouts when I was 10 and since then I love being one of them. I went under a proper scout leadership education, earning a decree allowing me to do my job. Being a troop leader requires lots of creativity, communication and managerial skills. The scouts movement raise, educate and train children and the youth to become independent, responsible, active and open minded citizens. I think that in my case it proved to be true."

    # Projects section
    [params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "C"
        level = "90%"

        [[params.skills.list]]
        skill = "Java"
        level = "75%"
                
        [[params.skills.list]]
        skill = "Python"
        level = "75%"

        [[params.skills.list]]
        skill = "Adobe Premiere"
        level = "75%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
