# Page settings

baseurl = "https://repik.sk/tomas/"
languageCode = "en-us"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    title = "Tomáš's CV"
    description = "Career profile"
    author = "Tomáš Repík"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Tomáš Repík"
        tagline = "Software engineer"
        avatar = "profile.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "location"
        icon = "fa-home"
        url = "https://goo.gl/maps/6gFmW6i9JaC2"
        title = "Bratislava, Slovakia"

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
#        url = "mailto: tomas@repik.sk"
#        title = "tomas@repik.sk"
        url = "mailto: tomm.momi@gmail.com"
        title = "tomm.momi@gmail.com"
#        url = "mailto: tomas.repik@instarea.com"
#        title = "tomas.repik@instarea.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+421903804847"
        title = "+421 903 804 847"

#        [[params.contact.list]]
#        class = "website"
#        icon = "fa-globe"
#        url = "//portfoliosite.com"
#        title = "portfoliosite.com"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/trepik"
        title = "github.com/trepik"

    # Languages section
    [params.languages]
        enable = true
        title = "Languages"

        [[params.languages.list]]
        language = "Slovak"
        level = "Native"

        [[params.languages.list]]
        language = "Czech"
        level = "Native"

        [[params.languages.list]]
        language = "English"
        level = "Professional"

        [[params.languages.list]]
        language = "Spanish"
        level = "Passive"

        [[params.languages.list]]
        language = "German"
        level = "Passive"

    # Interests section
    [params.interests]
        enable = false
        title = "Interests"

        [[params.interests.list]]
        interest = "Outdoor activities"

        [[params.interests.list]]
        interest = "Motorsport"

        [[params.interests.list]]
        interest = "Guitar Music"

    # Cares section
    [params.cares]
        enable = true
        title = "Cares about"

        [[params.cares.list]]
        cares = "Healthy and honest relationships"

        [[params.cares.list]]
        cares = "Sustainable life style"

        [[params.cares.list]]
        cares = "Spreading knowledge"

    # Wonders section
    [params.wonders]
        enable = true
        title = "Wonders"
        question = "What will our chilldren say was the best thing we did for them nowdays?"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "About me"
        summary = "As a father of two young children I recently rediscovered the passion for asking why. Actually questioning the status quo is one of the constants in my life. How does this work? Why do we do it like this? Can we do it in another, maybe better way? These are the questions I am asking a lot. Haveing some basic knowledge or expertise is key to be worthy in any society. Understanding and viewing the current state/process/problem from different perspectives is a solid ground for makeing improvement. Then there is this leap of faith into the unknown of trying new things and possibly also making mistakes. But with courage, creativity and persitestence onboard there is very high probability of success."

    # Education section
    [params.education]
        enable = true
        icon = "fa-graduation-cap"
        title = "Education"

        [[params.education.list]]
        degree = "Kanban practitioner"
        college = "Kanban university"
        dates = "2022"

        [[params.education.list]]
        degree = "Reactive architecture"
        college = "Cognitive class"
        dates = "2018"

        [[params.education.list]]
        degree = "Master of Bioinformatics and Biocomputing"
        college = "Brno University of Technology"
        dates = "2015 - 2017"

        [[params.education.list]]
        degree = "Cluster Analysis and Data Mining"
        college = "Coursera"
        dates = "2015"

        [[params.education.list]]
        degree = "Semester at Computer Science Department"
        college = "University of Tennessee Chattanooga"
        dates = "2015"

        [[params.education.list]]
        degree = "Bachelor of Information Technology"
        college = "Brno University of Technology"
        dates = "2010 - 2014"

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Data specialist in spare parts management"
        dates = "2020 - present"
        company = "Lenovo, Bratislava"
        details = "I'm part of a small team supporting business people with answers. These answers are usually needed fast and precise, based on data of vast volumes spread around many systems. Data visualization is my dominant power, but behind the scenes there is lots of data integration (APIs), processing and management. We're also called automation team as we're transforming many processes done manualy into automated solutions. As an exchange for my technical expertise I learnd a lot about logistics, planning and business partner management."

        [[params.jobs.list]]
        position = "Coordinator of waste management at Christmas market"
        dates = "December 2019"
        company = "The capital city of Slovakia, Bratislava"
        details = "When this position was opened I could not resist to try it out. Being respnosible for for the whole waste sortation process included: managing shifts of workers, watching over them at sortaton stations as well as watching over businesses and their waste management. Reporting to mayor and his team on how the process is going and what can be improved for next years, was just a cherry on top of this great experience."

        [[params.jobs.list]]
        position = "Data scientist / Software Engineer / Team lead"
        dates = "2017 - 2019"
        company = "Instarea, Bratislava"
        details = "Becoming data scientist was one of my dreams come true. Directing huge loads of data to find its place and show its value was one of my first tasks. I was also responsible for bussines intelligence and data visualization, done primarly in PowerBI. Then I've been working on a project of peopleless sauna, building up an ecosystem (consiting of mobile APPs and IOT devices) from scratch. Apart from development I was also coordinating a team of 5 people working on the solution."

        [[params.jobs.list]]
        position = "Associate Software Engineer"
        dates = "2015 - 2017"
        company = "Red Hat, Brno"
        details = "I was a package maintainer for both Fedora and Red Hat Enterprise Linux. My work included Java and C, but also scripting in bash or Python. Besides the basic bug-fixing or RPMs, I came across technologies like Software Collections and Containers."

        [[params.jobs.list]]
        position = "Scout Troop Leader"
        dates = "2010 - 2022"
        company = "29. troop Albatrosi, Bratislava"
        details = "I joined scouts when I was 10 and since then I love being one of them. I went under a proper scout leadership education, earning a decree. Being a troop leader requires lots of creativity, communication and managerial skills. The scout movement raise, educate and train children and the youth to become independent, responsible, active and open minded citizens. I think that in my case it proved to be true."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
#        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "ElysiumSpa"
        url = "https://elysiumspa.sk"
        tagline = "At Instarea we started to implement our own IOT solution for peopleless smart saunas. Building up a database as a center point of truth was my first task. Then I created a mobile APP for controlling all IOT devices in the sauna. Some automation was necessary and for that NodeRED flows were implemented. After the ideas came alive and more people started to get involved my role included more management task as I became the technical lead of the project."

        [[params.projects.list]]
        title = "Maxpoweleague"
        url = "https://www.youtube.com/maxpowerleague"
        tagline = "During my studies I had been part of an online racing community around rFactor racing simulator. Ever since I joined I participated in organization of the events. I wrote reports, managed website and result system, cut video reports and commented on live broadcasts."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "SQL Database (SQL Server, MySQL, PostrgeSQL)"
        level = "90%"

        [[params.skills.list]]
        skill = "Data visualization tools (PowerBI)"
        level = "90%"

        [[params.skills.list]]
        skill = "New technologies (ClickHouse, OmniSci, Cassandra, Hugo, Docker)"
        level = "80%"

        [[params.skills.list]]
        skill = "Programming languages (GO, Python, C#, Java, C, Bash)"
        level = "80%"

        [[params.skills.list]]
        skill = "Internet of Things (Mosquitto, Node-RED)"
        level = "70%"

        [[params.skills.list]]
        skill = "Web development (HTML, CSS, JavaScript, PHP, Joomla, Wordpress)"
        level = "50%"

        [[params.skills.list]]
        skill = "Multimedia tools (Adobe Premiere, Photoshop)"
        level = "40%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]

        copyright = ""
